variable "name" {
  type        = string
  description = "The name of the K8S deployment lambda and its resources"
}

variable "namespace" {
  type        = string
  description = "Kubernetes namespace"
  default     = "default"
}


variable "create_role" {
  type        = bool
  description = "Whether to create or not the IAM Role for the lambda function"
  default     = true
}

variable "existing_role_arn" {
  type        = string
  description = "The ARN of an existing IAM role to be used for this deployment."
  default     = null
}

variable "tfstate_s3_bucket" {
  type        = string
  description = "Terraform tfstate s3 bucket ARN"
  default     = ""
}

variable "artifacts_s3_bucket" {
  type        = string
  description = "Artifacts S3 Bucket ARN - on this bucket, we store the packages generated by Github Actions builds (.zip files)"
  default     = ""
}

variable "dynamodb_tables_list" {
  type        = list(string)
  description = "DynamoDb tables arns where the k8s deployment iam role has access"
  default     = []
}

variable "role_path" {
  description = "Path of IAM role"
  type        = string
  default     = "/"
}

variable "role_permissions_boundary_arn" {
  description = "Permissions boundary ARN to use for IAM role"
  type        = string
  default     = null
}

variable "role_description" {
  description = "IAM Role description"
  type        = string
  default     = null
}

variable "role_name_prefix" {
  description = "IAM role name prefix"
  type        = string
  default     = null
}

variable "policy_name_prefix" {
  description = "IAM policy name prefix"
  type        = string
  default     = "aws"
}

variable "tags" {
  description = "A map of tags to add the the IAM role"
  type        = map(any)
  default     = {}
}


variable "oidc_providers" {
  description = "Map of OIDC providers where each provider map should contain the `provider`, `provider_arn`, and `namespace_service_accounts`"
  type        = any
  default     = {}
}

variable "force_detach_policies" {
  description = "Whether policies should be detached from this role when destroying"
  type        = bool
  default     = true
}

variable "max_session_duration" {
  description = "Maximum CLI/API session duration in seconds between 3600 and 43200"
  type        = number
  default     = null
}

variable "role_name" {
  description = "Name of IAM role"
  type        = string
  default     = null
}

variable "role_policy_arns" {
  description = "ARNs of any policies to attach to the IAM role"
  type        = set(string)
  default     = []
}


variable "secrets" {
  description = "List of secret that will be used by the SecretsStore."
  type        = list(string)
  default     = []
}

variable "env_vars" {
  description = "Map of environment variables to set for the Lambda function."
  type        = map(string)
  default     = {}
}
