apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "axetrading-deployment-dependencies.fullname" . }}-deployment-script
  labels:
  {{- include "axetrading-deployment-dependencies.labels" . | nindent 4 }}
data:
  deploy.sh: {{ .Values.terraformUpdateConfigmap.deploySh | toYaml | indent 1 }}