apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "axetrading-deployment-dependencies.fullname" . }}
  labels:
  {{- include "axetrading-deployment-dependencies.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "axetrading-deployment-dependencies.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "axetrading-deployment-dependencies.fullname" . }}
  namespace: '{{ .Release.Namespace }}'