apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "axetrading-deployment-dependencies.fullname" . }}
  labels:
  {{- include "axetrading-deployment-dependencies.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - jobs
  - configmaps
  - deployments
  verbs:
  - create
  - read
  - update
  - patch
  - delete