{{- if .Values.secretsStore.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ template "axetrading-deployment-dependencies.fullname" . }}-secrets
  labels:
    {{- include "axetrading-deployment-dependencies.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  provider: {{ .Values.secretsStore.provider }}
  parameters:
    {{- if .Values.secretsStore.awsSecrets }}
    objects: |
      {{- range $_, $secret := .Values.secretsStore.awsSecrets }}
        - objectName: {{ $secret }}
          objectType: "secretsmanager"
      {{- end }}
    {{- end }}
{{- end }}
