{{- if .Values.secretsStore.enabled }}
  {{- range $index, $secret := .Values.secretsStore.secretProviderClasses }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ (replace "/" "-" $secret) }}-secrets
  labels:
    usedBy: {{ (replace "/" "-" $secret) }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  provider: {{ $.Values.secretsStore.provider }}
  parameters:
    objects: |
      - objectName: {{ $secret }}
        objectType: "secretsmanager"
  {{- end }}
{{- end }}
